version: "3"
services:
  server:
    build: .
    links:
    - db
    ports:
    - 5000:5000
    command: ["node_modules/.bin/nodemon", "src/index.js"]
    volumes:
    - .:/usr/srv/app
    - /usr/srv/app/node_modules

  db:
    image: cockroachdb/cockroach:v1.1.5
    ports:
    - 8080:8080
    - 26257:26257
    volumes:
    - ./cockroach-data/db:/cockroach/cockroach-data
    command: ['start', '--insecure']
